version: "3.8"
services:
  restaurant_web:
    build: .
    volumes:
      - .:/restaurant_website
    ports:
      - 8000:8000
    image: restaurant_web:restaurant_website_image
    container_name: restaurant_website_container
    command: python manage.py runserver 0.0.0.0:8000